name: install
on:
  workflow_call:
runs:
  using: "composite"
  steps:
    - run: pip install poetry
      shell: bash
    - run: poetry config virtualenvs.create false
      shell: bash
    - run: poetry install -n --no-dev
      shell: bash
      working-directory: review